# Generated by Django 5.0.1 on 2025-05-06 07:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='external_id',
            field=models.CharField(blank=True, help_text='ID from external calendar system', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='external_source',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('apple_calendar', 'Apple Calendar'), ('google_calendar', 'Google Calendar'), ('caldav', 'Other CalDAV')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='last_synced',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence_rule',
            field=models.CharField(blank=True, help_text='iCalendar RRULE string', max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['external_id'], name='planner_eve_externa_b12468_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start_time'], name='planner_eve_start_t_ce37df_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['family', 'start_time'], name='planner_eve_family__fea01c_idx'),
        ),
    ]
