# Generated by Django 5.2 on 2025-05-05 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalDavSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_url', models.URLField(help_text='URL des CalDAV-Servers')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('enabled', models.BooleanField(default=True, help_text='CalDAV-Integration aktivieren/deaktivieren')),
                ('sync_interval', models.IntegerField(default=30, help_text='Synchronisationsintervall in Minuten')),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('available_calendars', models.JSONField(blank=True, null=True)),
                ('family', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='caldav_settings', to='planner.family')),
            ],
            options={
                'verbose_name': 'CalDAV-Einstellung',
                'verbose_name_plural': 'CalDAV-Einstellungen',
            },
        ),
        migrations.CreateModel(
            name='CalDavCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_url', models.URLField()),
                ('calendar_name', models.CharField(max_length=255)),
                ('color', models.CharField(default='#3788d8', help_text='Farbe des Kalenders in HEX-Format', max_length=7)),
                ('enabled', models.BooleanField(default=True)),
                ('caldav_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendars', to='external_services.caldavsettings')),
            ],
            options={
                'verbose_name': 'CalDAV-Kalender',
                'verbose_name_plural': 'CalDAV-Kalender',
            },
        ),
        migrations.CreateModel(
            name='WeatherSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(blank=True, help_text='API-Schlüssel für den Wetterdienst', max_length=255, null=True)),
                ('location', models.CharField(default='Dornbirn', help_text='Standardort für Wetterabfragen', max_length=255)),
                ('enabled', models.BooleanField(default=True, help_text='Wetterdienst aktivieren/deaktivieren')),
                ('update_interval', models.IntegerField(default=10, help_text='Aktualisierungsintervall in Minuten')),
                ('last_weather_data', models.JSONField(blank=True, null=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('family', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='weather_settings', to='planner.family')),
            ],
            options={
                'verbose_name': 'Wetter-Einstellung',
                'verbose_name_plural': 'Wetter-Einstellungen',
            },
        ),
    ]
