# Generated by Django 5.0.1 on 2025-05-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caldavcalendar',
            name='calendar_id',
            field=models.CharField(blank=True, help_text='Calendar ID or path', max_length=255),
        ),
        migrations.AddField(
            model_name='caldavcalendar',
            name='last_sync',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caldavsettings',
            name='last_sync',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caldavsettings',
            name='provider',
            field=models.CharField(choices=[('apple', 'Apple Calendar'), ('google', 'Google Calendar'), ('nextcloud', 'Nextcloud'), ('generic', 'Generic CalDAV')], default='apple', max_length=20),
        ),
        migrations.AddField(
            model_name='caldavsettings',
            name='sync_frequency',
            field=models.IntegerField(default=15, help_text='Sync frequency in minutes'),
        ),
        migrations.AlterField(
            model_name='caldavcalendar',
            name='calendar_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='caldavsettings',
            name='base_url',
            field=models.CharField(default='https://caldav.icloud.com', help_text='For Apple Calendar, use https://caldav.icloud.com', max_length=255),
        ),
        migrations.AlterField(
            model_name='caldavsettings',
            name='password',
            field=models.CharField(help_text='For Apple Calendar, use an app-specific password', max_length=255),
        ),
        migrations.AlterField(
            model_name='caldavsettings',
            name='username',
            field=models.CharField(help_text='For Apple Calendar, use your Apple ID', max_length=100),
        ),
    ]
